### ISSUE TITLE
Switch to PSR-12

### ISSUE THREAD

**Issue by xepozz** [yiisoft/template#4]
https://github.styleci.io/analyses/KZDjyR?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

`psr-2` preset in StyleCI does not support typed properties. 
I think switching to `psr-12` will solve it.

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  7.4
| Operating system |

**Comment by samdark** [comment]
Yes but StyleCI does't support PSR-12. As far as I know, StyleCI is planning to add the support Q2 2020.

**Comment by rob006** [comment]
This error is not related to PSR-12, but PHP version used by sctyleci (looks like this file is parsed by PHP <7.4, so it is not able to recognize type before property name).

**Comment by xepozz** [comment]
I found it in https://github.com/yiisoft/yii-web/pull/191
[Composer have 7.4 version](https://github.com/yiisoft/yii-web/blob/master/composer.json#L20)

**Comment by samdark** [comment]
Ah, that. 7.4 support "is planned Q1 2020 (maybe even as soon as December 2019)".

**Comment by samdark** [comment]
Done by now.
